name: Python application

on:
    push: 
        branches: ["main"]

permissions:
    contents: read

jobs:
    review:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with: 
                python-version: "3.11.9"
            - name: Install Dependencies
              run: pip install -r requirements.txt
            - name: run Review Script
              env:
                EMAIL_SERVICE: ${{secrets.EMAIL_SERVICE}}
                GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
              run: python ./scripts/review.py